# Generated by Django 3.1.1 on 2020-10-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201015_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='status',
            new_name='name',
        ),
    ]
