# Generated by Django 3.1.1 on 2020-10-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201019_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
