# Generated by Django 3.1.1 on 2020-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='note',
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
