# Generated by Django 3.1.1 on 2020-11-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201126_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, default='general order', max_length=200, null=True),
        ),
    ]
