# Generated by Django 3.1.1 on 2020-11-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201127_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(default='general order', max_length=200, null=True),
        ),
    ]
