# Generated by Django 3.1.1 on 2020-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/download.png', null=True, upload_to=''),
        ),
    ]
